In [108]:
import pandas as pd

# Define the file paths
file_2018 = 'grouped_by_state_2018.csv'
file_2024 = 'grouped_by_state_2024.csv'

# Read the CSV files
df_2018 = pd.read_csv(file_2018, encoding='latin1')
df_2024 = pd.read_csv(file_2024, encoding='latin1')

# Display the first few rows of each DataFrame to understand their structure
print("2018 DataFrame:")
df_2018.head(32)

2018 DataFrame:

,ENTIDAD,AMLO,Meade,Jaime,Margarita,Anaya,NULOS,Total Votes,AMLO %,Meade %,Jaime %,Margarita %,Anaya %,NULOS %
0,AGUASCALIENTES,190820.0,91229.0,33776.0,873.0,156789.0,12965.0,486452.0,39.23,18.75,6.94,0.18,32.23,2.67
1,BAJA CALIFORNIA,675810.0,95073.0,67433.0,1293.0,206904.0,23499.0,1070012.0,63.16,8.89,6.30,0.12,19.34,2.20
2,BAJA CALIFORNIA SUR,136806.0,20147.0,12050.0,440.0,40277.0,4760.0,214480.0,63.78,9.39,5.62,0.21,18.78,2.22
3,CAMPECHE,171328.0,61560.0,6974.0,319.0,34320.0,7620.0,282121.0,60.73,21.82,2.47,0.11,12.16,2.70
4,CHIAPAS,1106665.0,417732.0,29302.0,2693.0,150139.0,101463.0,1807994.0,61.21,23.10,1.62,0.15,8.30,5.61
5,CHIHUAHUA,441965.0,176103.0,90398.0,3067.0,298972.0,32809.0,1043314.0,42.36,16.88,8.66,0.29,28.66,3.14
6,CIUDAD DE MEXICO,2670615.0,571719.0,191794.0,5662.0,1131245.0,98186.0,4669221.0,57.20,12.24,4.11,0.12,24.23,2.10
7,COAHUILA,515518.0,306343.0,59080.0,1811.0,265532.0,22749.0,1171033.0,44.02,26.16,5.05,0.15,22.68,1.94
8,COLIMA,178123.0,57421.0,14651.0,338.0,51434.0,8396.0,310363.0,57.39,18.50,4.72,0.11,16.57,2.71
9,DURANGO,247076.0,100387.0,34716.0,824.0,140865.0,13462.0,537330.0,45.98,18.68,6.46,0.15,26.22,2.51
10,GUANAJUATO,608766.0,330697.0,187231.0,3987.0,820676.0,62191.0,2013548.0,30.23,16.42,9.30,0.20,40.76,3.09
11,GUERRERO,844065.0,243320.0,20359.0,1265.0,187012.0,54041.0,1350062.0,62.52,18.02,1.51,0.09,13.85,4.00
12,HIDALGO,744219.0,229980.0,52597.0,1380.0,168049.0,33066.0,1229291.0,60.54,18.71,4.28,0.11,13.67,2.69
13,JALISCO,1181823.0,421929.0,197584.0,5596.0,978323.0,83924.0,2869179.0,41.19,14.71,6.89,0.20,34.10,2.93
14,MEXICO,3552823.0,1271892.0,306638.0,7397.0,1269222.0,148997.0,6556969.0,54.18,19.40,4.68,0.11,19.36,2.27
15,MICHOACAN,820449.0,275139.0,99972.0,3218.0,365506.0,71802.0,1636086.0,50.15,16.82,6.11,0.20,22.34,4.39
16,MORELOS,521571.0,83762.0,47427.0,1422.0,115045.0,21660.0,790887.0,65.95,10.59,6.00,0.18,14.55,2.74
17,NAYARIT,240273.0,49081.0,8160.0,339.0,60796.0,8973.0,367622.0,65.36,13.35,2.22,0.09,16.54,2.44
18,NUEVO LEON,551927.0,238337.0,262155.0,4728.0,548726.0,37560.0,1643433.0,33.58,14.50,15.95,0.29,33.39,2.29
19,OAXACA,1077520.0,292439.0,34426.0,1754.0,188740.0,57503.0,1652382.0,65.21,17.70,2.08,0.11,11.42,3.48
20,PUEBLA,1450901.0,401622.0,94803.0,3292.0,507230.0,82792.0,2540640.0,57.11,15.81,3.73,0.13,19.96,3.26
21,QUERETARO,350246.0,121532.0,61108.0,1578.0,288129.0,22826.0,845419.0,41.43,14.38,7.23,0.19,34.08,2.70
22,QUINTANA ROO,334458.0,53381.0,20777.0,624.0,80001.0,12483.0,501724.0,66.66,10.64,4.14,0.12,15.95,2.49
23,SAN LUIS POTOSI,413328.0,206889.0,63050.0,1602.0,261711.0,43284.0,989864.0,41.76,20.90,6.37,0.16,26.44,4.37
24,SINALOA,632646.0,181254.0,21646.0,954.0,125773.0,25540.0,987813.0,64.05,18.35,2.19,0.10,12.73,2.59
25,SONORA,462120.0,131504.0,45027.0,1403.0,124893.0,20161.0,785108.0,58.86,16.75,5.74,0.18,15.91,2.57
26,TABASCO,766515.0,87337.0,7631.0,532.0,75268.0,24509.0,961792.0,79.70,9.08,0.79,0.06,7.83,2.55
27,TAMAULIPAS,607278.0,182470.0,82881.0,2169.0,380290.0,28093.0,1283181.0,47.33,14.22,6.46,0.17,29.64,2.19
28,TLAXCALA,358631.0,65698.0,21502.0,642.0,56939.0,10416.0,513828.0,69.80,12.79,4.18,0.12,11.08,2.03
29,VERACRUZ,1780983.0,414481.0,112431.0,3198.0,905466.0,86474.0,3303033.0,53.92,12.55,3.40,0.10,27.41,2.62
30,YUCATAN,330914.0,226568.0,29184.0,793.0,230173.0,17950.0,835582.0,39.60,27.11,3.49,0.09,27.55,2.15
31,ZACATECAS,307197.0,151462.0,31024.0,997.0,134541.0,19812.0,645033.0,47.63,23.48,4.81,0.15,20.86,3.07

In [109]:

print("\n2024 DataFrame:")
df_2024.head()

2024 DataFrame:

,ENTIDAD,Xochitl,Claudia,Maynez,NULOS,Urban_polling_stations,Non_urban_polling_stations,Total Votes,Xochitl %,Claudia %,Maynez %,NULOS %
0,AGUASCALIENTES,294746.0,270389.0,57054.0,14144.0,1279,563,636333.0,46.32,42.49,8.97,2.22
1,BAJA CALIFORNIA,290698.0,862661.0,132914.0,30287.0,4671,703,1316560.0,22.08,65.52,10.10,2.30
2,BAJA CALIFORNIA SUR,90838.0,175755.0,26581.0,6443.0,827,287,299617.0,30.32,58.66,8.87,2.15
3,CAMPECHE,62268.0,240693.0,82898.0,9346.0,734,496,395205.0,15.76,60.90,20.98,2.36
4,CHIAPAS,355592.0,1519559.0,162166.0,94634.0,2519,4354,2131951.0,16.68,71.28,7.61,4.44

In [110]:
# Inspect the DataFrames
print("Columnas de 2018:")
print(df_2018.columns)

print("\nColumnas de 2024:")
print(df_2024.columns)

Columnas de 2018:
Index(['ENTIDAD', 'AMLO', 'Meade', 'Jaime', 'Margarita', 'Anaya', 'NULOS',
       'Total Votes', 'AMLO %', 'Meade %', 'Jaime %', 'Margarita %', 'Anaya %',
       'NULOS %'],
      dtype='object')

Columnas de 2024:
Index(['ENTIDAD', 'Xochitl', 'Claudia', 'Maynez', 'NULOS',
       'Urban_polling_stations', 'Non_urban_polling_stations', 'Total Votes',
       'Xochitl %', 'Claudia %', 'Maynez %', 'NULOS %'],
      dtype='object')

In [111]:
# Filtrar las columnas relevantes
df_2018 = df_2018[['ENTIDAD', 'AMLO']]
df_2024 = df_2024[['ENTIDAD', 'Claudia', 'Xochitl', 'Maynez', 'NULOS','Urban_polling_stations', 'Non_urban_polling_stations']]

# rename 'AMLO' to 'AMLO_2018' to understand is historic data
df_2018.rename(columns={'AMLO': 'AMLO_2018'}, inplace=True)

LEFT JOIN OF BOTH dataframes

In [112]:
# Unir los DataFrames en base a la columna 'ENTIDAD'
df_combined = pd.merge(df_2024, df_2018, on='ENTIDAD', how='left')

# Mostrar las primeras filas del DataFrame combinado
df_combined.head(32)

,ENTIDAD,Claudia,Xochitl,Maynez,NULOS,Urban_polling_stations,Non_urban_polling_stations,AMLO_2018
0,AGUASCALIENTES,270389.0,294746.0,57054.0,14144.0,1279,563,190820.0
1,BAJA CALIFORNIA,862661.0,290698.0,132914.0,30287.0,4671,703,675810.0
2,BAJA CALIFORNIA SUR,175755.0,90838.0,26581.0,6443.0,827,287,136806.0
3,CAMPECHE,240693.0,62268.0,82898.0,9346.0,734,496,171328.0
4,CHIAPAS,1519559.0,355592.0,162166.0,94634.0,2519,4354,1106665.0
5,CHIHUAHUA,744823.0,495324.0,135550.0,36676.0,4601,1160,441965.0
6,CIUDAD DE MEXICO,2978243.0,1862780.0,454084.0,100406.0,13166,265,2670615.0
7,COAHUILA,813432.0,595270.0,84184.0,34747.0,3307,836,515518.0
8,COLIMA,182063.0,102288.0,45426.0,7097.0,667,362,178123.0
9,DURANGO,402566.0,227617.0,51520.0,15436.0,1530,1088,247076.0
10,GUANAJUATO,1223770.0,1057455.0,278420.0,57357.0,5044,3100,608766.0
11,GUERRERO,1039283.0,276953.0,95579.0,45645.0,2304,2800,844065.0
12,HIDALGO,1001963.0,299831.0,156217.0,36334.0,1518,2692,744219.0
13,JALISCO,1592942.0,1303587.0,631761.0,84830.0,7782,3081,1181823.0
14,MEXICO,4916419.0,2177817.0,876926.0,179058.0,16527,4452,3552823.0
15,MICHOACAN,1033704.0,562486.0,232501.0,64066.0,3494,2936,820449.0
16,MORELOS,578230.0,195923.0,117582.0,18854.0,1956,621,521571.0
17,NAYARIT,306423.0,102576.0,67984.0,12797.0,1110,706,240273.0
18,NUEVO LEON,1062016.0,839701.0,432115.0,49533.0,6277,1164,551927.0
19,OAXACA,1367731.0,261778.0,119132.0,47299.0,2232,3687,1077520.0
20,PUEBLA,2066399.0,694569.0,322725.0,94196.0,5076,3243,1450901.0
21,QUERETARO,585662.0,428194.0,109805.0,26797.0,1773,1365,350246.0
22,QUINTANA ROO,536134.0,129343.0,57373.0,16493.0,1938,558,334458.0
23,SAN LUIS POTOSI,773086.0,330455.0,138705.0,41699.0,2031,1875,413328.0
24,SINALOA,782221.0,301345.0,95577.0,26388.0,3538,1621,632646.0
25,SONORA,674746.0,270687.0,99032.0,23814.0,2983,916,462120.0
26,TABASCO,811270.0,115104.0,61696.0,24801.0,1531,1580,766515.0
27,TAMAULIPAS,910332.0,390288.0,139605.0,31906.0,3795,1157,607278.0
28,TLAXCALA,486946.0,106484.0,98955.0,15194.0,1283,438,358631.0
29,VERACRUZ,2300252.0,810805.0,281570.0,84198.0,5796,5189,1780983.0
30,YUCATAN,696450.0,365357.0,81057.0,23358.0,2195,769,330914.0
31,ZACATECAS,369235.0,223133.0,124548.0,20082.0,1112,1522,307197.0

ORIGINALLY 7 NULL VALUES WHEN JOINING BECAUSE SOME ENTITY NAMES HAD APOSTROPHY IN ONE OF THE TABLES.
EG. MEXICO VS MÉXICO.
THIS WAS FIXED FROM ORIGIN AND NOW NULL VALUES ARE CERO:

In [113]:
df_combined.isnull().sum()

ENTIDAD                       0
Claudia                       0
Xochitl                       0
Maynez                        0
NULOS                         0
Urban_polling_stations        0
Non_urban_polling_stations    0
AMLO_2018                     0
dtype: int64

In [114]:
economic_data_path = './ECONOMIC_FEATURES/Simplified_PIB_Per_State.csv'
df_economic = pd.read_csv(economic_data_path, encoding='latin1')
df_economic.head()

,ï»¿ENTIDAD,PIB_1982,PIB_1988,PIB_1994,PIB_2000,PIB_2006,PIB_2012,PIB_2018,PIB_2024
0,Estados Unidos Mexicanos,"11,518,364.73","11,502,672.93","14,507,764.34","17,811,854.38","19,838,803.94","21,539,027.00","24,176,670.38","24,220,853.91"
1,Aguascalientes,"83,133.48","86,482.20","121,683.61","158,299.88","200,318.27","242,758.41","327,926.31","316,500.20"
2,Baja California,"446,781.45","417,816.04","548,270.48","790,646.79","772,686.81","726,418.11","878,816.87","929,458.73"
3,Baja California Sur,"58,188.20","62,347.41","75,145.06","95,187.28","126,685.37","147,269.70","184,618.10","177,420.70"
4,Campeche,"559,721.99","588,026.45","713,798.60","826,278.19","959,641.06","691,262.00","564,591.06","473,100.97"

In [115]:
df_economic.rename(columns={df_economic.columns[0]: 'ENTIDAD'}, inplace=True)
df_economic.head()

,ENTIDAD,PIB_1982,PIB_1988,PIB_1994,PIB_2000,PIB_2006,PIB_2012,PIB_2018,PIB_2024
0,Estados Unidos Mexicanos,"11,518,364.73","11,502,672.93","14,507,764.34","17,811,854.38","19,838,803.94","21,539,027.00","24,176,670.38","24,220,853.91"
1,Aguascalientes,"83,133.48","86,482.20","121,683.61","158,299.88","200,318.27","242,758.41","327,926.31","316,500.20"
2,Baja California,"446,781.45","417,816.04","548,270.48","790,646.79","772,686.81","726,418.11","878,816.87","929,458.73"
3,Baja California Sur,"58,188.20","62,347.41","75,145.06","95,187.28","126,685.37","147,269.70","184,618.10","177,420.70"
4,Campeche,"559,721.99","588,026.45","713,798.60","826,278.19","959,641.06","691,262.00","564,591.06","473,100.97"

In [116]:
# Merge the combined data with economic data
df_with_PIB = pd.merge(df_combined, df_economic, on='ENTIDAD', how='left')

In [117]:
df_with_PIB.head()

,ENTIDAD,Claudia,Xochitl,Maynez,NULOS,Urban_polling_stations,Non_urban_polling_stations,AMLO_2018,PIB_1982,PIB_1988,PIB_1994,PIB_2000,PIB_2006,PIB_2012,PIB_2018,PIB_2024
0,AGUASCALIENTES,270389.0,294746.0,57054.0,14144.0,1279,563,190820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BAJA CALIFORNIA,862661.0,290698.0,132914.0,30287.0,4671,703,675810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BAJA CALIFORNIA SUR,175755.0,90838.0,26581.0,6443.0,827,287,136806.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAMPECHE,240693.0,62268.0,82898.0,9346.0,734,496,171328.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CHIAPAS,1519559.0,355592.0,162166.0,94634.0,2519,4354,1106665.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
df_with_PIB.isnull().sum()

ENTIDAD                        0
Claudia                        0
Xochitl                        0
Maynez                         0
NULOS                          0
Urban_polling_stations         0
Non_urban_polling_stations     0
AMLO_2018                      0
PIB_1982                      32
PIB_1988                      32
PIB_1994                      32
PIB_2000                      32
PIB_2006                      32
PIB_2012                      32
PIB_2018                      32
PIB_2024                      32
dtype: int64

Now the error of not merging correctly is due to capital letters. Lets fix it...

In [119]:
# Convert state names to uppercase
df_2018['ENTIDAD'] = df_2018['ENTIDAD'].str.upper()
df_2024['ENTIDAD'] = df_2024['ENTIDAD'].str.upper()
df_economic['ENTIDAD'] = df_economic['ENTIDAD'].str.upper()

In [120]:
# Merge the combined data with economic data
df_with_PIB = pd.merge(df_combined, df_economic, on='ENTIDAD', how='left')

In [121]:
df_with_PIB.head(32)

,ENTIDAD,Claudia,Xochitl,Maynez,NULOS,Urban_polling_stations,Non_urban_polling_stations,AMLO_2018,PIB_1982,PIB_1988,PIB_1994,PIB_2000,PIB_2006,PIB_2012,PIB_2018,PIB_2024
0,AGUASCALIENTES,270389.0,294746.0,57054.0,14144.0,1279,563,190820.0,"83,133.48","86,482.20","121,683.61","158,299.88","200,318.27","242,758.41","327,926.31","316,500.20"
1,BAJA CALIFORNIA,862661.0,290698.0,132914.0,30287.0,4671,703,675810.0,"446,781.45","417,816.04","548,270.48","790,646.79","772,686.81","726,418.11","878,816.87","929,458.73"
2,BAJA CALIFORNIA SUR,175755.0,90838.0,26581.0,6443.0,827,287,136806.0,"58,188.20","62,347.41","75,145.06","95,187.28","126,685.37","147,269.70","184,618.10","177,420.70"
3,CAMPECHE,240693.0,62268.0,82898.0,9346.0,734,496,171328.0,"559,721.99","588,026.45","713,798.60","826,278.19","959,641.06","691,262.00","564,591.06","473,100.97"
4,CHIAPAS,1519559.0,355592.0,162166.0,94634.0,2519,4354,1106665.0,"213,802.07","230,321.52","281,576.82","309,796.91","321,113.55","370,237.30","353,600.11","368,788.56"
5,CHIHUAHUA,744823.0,495324.0,135550.0,36676.0,4601,1160,441965.0,"334,520.59","326,595.35","417,236.56","581,263.82","635,597.82","711,480.76","853,322.80","919,617.14"
6,CIUDAD DE MEXICO,2978243.0,1862780.0,454084.0,100406.0,13166,265,2670615.0,"2,017,375.62","1,897,079.43","2,448,263.34","2,903,708.82","3,134,225.22","3,332,208.72","3,694,574.87","3,640,387.94"
7,COAHUILA,813432.0,595270.0,84184.0,34747.0,3307,836,515518.0,"400,947.44","387,781.18","479,739.94","655,490.87","798,549.10","870,634.53","966,054.66","922,287.37"
8,COLIMA,182063.0,102288.0,45426.0,7097.0,667,362,178123.0,"69,593.67","74,614.04","90,021.40","110,550.51","114,843.83","135,599.87","153,808.39","148,129.75"
9,DURANGO,402566.0,227617.0,51520.0,15436.0,1530,1088,247076.0,"148,864.49","149,135.74","181,317.13","208,654.02","241,373.38","286,058.27","308,981.25","296,963.12"
10,GUANAJUATO,1223770.0,1057455.0,278420.0,57357.0,5044,3100,608766.0,"405,843.99","410,582.65","515,053.91","653,601.35","769,496.26","892,378.88","1,120,602.84","1,128,686.27"
11,GUERRERO,1039283.0,276953.0,95579.0,45645.0,2304,2800,844065.0,"204,231.27","210,191.00","244,535.13","256,193.56","280,082.84","294,551.28","317,844.94","306,830.77"
12,HIDALGO,1001963.0,299831.0,156217.0,36334.0,1518,2692,744219.0,"231,940.42","235,179.79","297,707.22","337,331.45","349,080.41","379,811.02","418,630.44","426,819.09"
13,JALISCO,1592942.0,1303587.0,631761.0,84830.0,7782,3081,1181823.0,"842,329.34","843,957.15","1,031,966.72","1,259,069.61","1,340,006.10","1,488,616.80","1,754,179.51","1,783,505.05"
14,MEXICO,4916419.0,2177817.0,876926.0,179058.0,16527,4452,3552823.0,"1,020,962.55","1,005,115.82","1,239,027.57","1,560,108.79","1,710,985.65","1,911,401.72","2,243,797.97","2,184,862.98"
15,MICHOACAN,1033704.0,562486.0,232501.0,64066.0,3494,2936,820449.0,"282,663.39","304,548.07","364,984.89","451,793.04","485,161.70","531,827.40","633,756.56","646,901.48"
16,MORELOS,578230.0,195923.0,117582.0,18854.0,1956,621,521571.0,"140,692.48","144,824.19","176,584.99","206,506.91","232,043.61","248,100.47","273,244.60","256,739.58"
17,NAYARIT,306423.0,102576.0,67984.0,12797.0,1110,706,240273.0,"85,672.90","87,659.18","112,712.61","115,655.77","135,896.56","142,897.86","155,757.54","161,868.68"
18,NUEVO LEON,1062016.0,839701.0,432115.0,49533.0,6277,1164,551927.0,"689,748.60","694,487.69","916,740.23","1,212,180.74","1,469,583.90","1,621,930.27","1,909,026.44","1,945,060.16"
19,OAXACA,1367731.0,261778.0,119132.0,47299.0,2232,3687,1077520.0,"262,454.68","268,784.77","344,896.49","355,730.60","380,271.45","386,537.70","383,159.65","407,238.09"
20,PUEBLA,2066399.0,694569.0,322725.0,94196.0,5076,3243,1450901.0,"336,332.44","344,990.46","425,377.90","563,688.53","650,292.57","747,711.78","849,556.00","820,789.75"
21,QUERETARO,585662.0,428194.0,109805.0,26797.0,1773,1365,350246.0,"197,183.53","189,848.46","266,657.53","368,560.57","427,146.95","526,760.65","611,367.75","592,138.82"
22,QUINTANA ROO,536134.0,129343.0,57373.0,16493.0,1938,558,334458.0,"99,390.22","102,517.02","140,495.16","180,224.21","234,332.56","280,380.54","377,340.67","357,538.61"
23,SAN LUIS POTOSI,773086.0,330455.0,138705.0,41699.0,2031,1875,413328.0,"203,667.93","201,730.86","264,259.32","310,464.57","377,360.11","437,595.48","557,795.95","537,933.22"
24,SINALOA,782221.0,301345.0,95577.0,26388.0,3538,1621,632646.0,"277,301.13","283,922.53","344,143.94","391,567.00","411,251.10","466,781.78","527,714.06","516,711.16"
25,SONORA,674746.0,270687.0,99032.0,23814.0,2983,916,462120.0,"342,667.23","329,333.28","446,592.63","591,564.06","605,738.98","681,378.52","782,097.74","804,668.18"
26,TABASCO,811270.0,115104.0,61696.0,24801.0,1531,1580,766515.0,"294,532.49","306,785.50","375,021.81","425,906.51","478,125.00","595,176.48","471,565.25","635,464.53"
27,TAMAULIPAS,910332.0,390288.0,139605.0,31906.0,3795,1157,607278.0,"331,231.13","336,905.19","419,239.84","565,664.82","657,147.38","676,616.01","732,093.58","746,945.74"
28,TLAXCALA,486946.0,106484.0,98955.0,15194.0,1283,438,358631.0,"68,237.90","69,999.49","87,364.99","112,212.24","117,236.12","128,974.60","147,752.94","143,717.42"
29,VERACRUZ,2300252.0,810805.0,281570.0,84198.0,5796,5189,1780983.0,"646,101.09","676,135.84","837,586.16","896,917.15","992,039.26","1,084,722.59","1,029,905.40","1,032,888.99"
30,YUCATAN,696450.0,365357.0,81057.0,23358.0,2195,769,330914.0,"140,424.34","145,505.23","187,126.78","232,449.32","270,589.95","299,649.18","364,797.90","369,864.39"
31,ZACATECAS,369235.0,223133.0,124548.0,20082.0,1112,1522,307197.0,"81,826.68","89,469.40","112,635.60","124,586.51","159,901.10","201,298.32","228,388.21","221,026.46"

In [122]:
df_with_PIB.isnull().sum()

ENTIDAD                       0
Claudia                       0
Xochitl                       0
Maynez                        0
NULOS                         0
Urban_polling_stations        0
Non_urban_polling_stations    0
AMLO_2018                     0
PIB_1982                      0
PIB_1988                      0
PIB_1994                      0
PIB_2000                      0
PIB_2006                      0
PIB_2012                      0
PIB_2018                      0
PIB_2024                      0
dtype: int64